-- ============================================================================
--  Migración V1: tabla de usuarios.
--
--  Flyway ejecuta este script una sola vez y registra su versión en la tabla
--  flyway_schema_history. Los tipos de columna están elegidos para coincidir
--  con el mapeo por defecto de Hibernate 6 (ddl-auto: validate).
-- ============================================================================

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Índice para acelerar la búsqueda por nombre de usuario (login).
CREATE INDEX idx_users_username ON users (username);
