-- ============================================================================
--  Migración V2: tabla de tareas.
--
--  Cada tarea pertenece a un usuario (user_id -> users.id). El borrado del
--  usuario elimina en cascada sus tareas (ON DELETE CASCADE).
-- ============================================================================

CREATE TABLE tasks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(150) NOT NULL,
    description TEXT,
    status      VARCHAR(20)  NOT NULL,           -- PENDIENTE / EN_PROGRESO / COMPLETADA
    due_date    DATE,
    user_id     BIGINT       NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_tasks_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Índice para listar/filtrar rápidamente las tareas de un usuario por estado.
CREATE INDEX idx_tasks_user_status ON tasks (user_id, status);
